version: '3.8'

networks:
  inception:
    name: inception

services:

  # NGINX
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    environment:
      CERTS_: ${CERTS_}
    networks:
      - inception
    restart: always

  # WORDPRESS
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always

  # MARIADB
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - inception
    restart: always

  # REDIS CACHE
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/njantsch/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/njantsch/data/wordpress
      o: bind
      type: none
