version: '3.8'

networks:
  inception:
    name: inception

services:
  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx
  #   ports:
  #     - "443:443"
  #   environment:
  #     CERTS_: ${CERTS_}
  #   networks:
  #     - inception
  #   restart: always

  # wordpress:
  #   build: ./requirements/wordpress
  #   depends_on:
  #     - mariadb
  #   environment:

  #   networks:
  #     - inception
  #   restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    # volumes:
    #   - mariadb:/home/njantsch/data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
    networks:
      - inception
    # restart: always

# volumes:
#   mariadb:
